http:
  port: 3000
  host: 13.229.207.6
apiEndpoints:
  api:
    host: 13.229.207.6
    paths: '/ip'
  user:
    host: 13.229.207.6
    paths: ['/updatepass', '/checksdt', '/dangnhap', '/id=:id', '/sdt=:sdt', '/']
  contact:
    host: 13.229.207.6
    paths: ['/getListFriend', '/getlistrequestfriend', '/getTrangThaiFriend','/deleterequest', '/acceptrequest']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url : 'https://54.254.201.191:4000'
  contactService:
    url : 'https://13.250.34.4:5000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
  contactPipeline:
    apiEndpoints:
      - contact
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: contactService 
              changeOrigin: true